sudo: required

language: python

services:
  - docker

before_install:
- docker build --build-arg travis_branch=${TRAVIS_BRANCH} --build-arg travis_pull_request=${TRAVIS_PULL_REQUEST} --build-arg kb_user=${KB_USER} --build-arg kb_password=${KB_PASSWORD} --build-arg kb_target_url=${KB_TARGET_URL} -t pivotal-gss/kb-docker .
- docker images

script:
#- docker run -it pivotalsupport/kb-docker
- docker run -it -v $PWD:/pcf-kbs -e TRAVIS_BRANCH="prod" -e KB_TARGET_URL=$KB_TARGET_URL -e KB_USER=$KB_USER -e KB_PASSWORD=$KB_PASSWORD  pivotalsupport/kb-docker /bin/sh
- docker ps -a
