sudo: required

language: python

services:
  - docker

before_install:
- docker build --build-arg travis_branch=${TRAVIS_BRANCH},travis_pull_request=${TRAVIS_PULL_REQUEST} -t pivotal-gss/kb-docker .
- docker images

script:
- docker run -it pivotal-gss/kb-docker
- docker ps -a
